[build]
  builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
  nixPkgs = ["nodejs_20"]

[build.nixpacksPlan.phases.install]
  cmds = [
    "cd frontend && npm install && npm run build && cd ..",
    "cd backend && npm install"
  ]

[start]
  cmd = "node backend/server.js"
